[package]
name = "disco-ball-gc"
version = "0.1.0"
authors = ["zypeh <zypeh.geek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.6.1" } # no_std crate